import os
import shutil
from pathlib import Path
import tkinter as tk
from tkinter import messagebox, filedialog
import json

CONFIG_PATH = Path.home() / ".ucs_sorter_config.json"

UCS_MAP = {
    "AIRBlow": ("AIR", "BLOW"),
    "AIRBrst": ("AIR", "BURST"),
    "AIRHiss": ("AIR", "HISS"),
    "AIRMisc": ("AIR", "MISC"),
    "AIRSuck": ("AIR", "SUCTION"),
    "AERODoor": ("AIRCRAFT", "DOOR"),
    "AEROHeli": ("AIRCRAFT", "HELICOPTER"),
    "AEROInt": ("AIRCRAFT", "INTERIOR"),
    "AEROJet": ("AIRCRAFT", "JET"),
    "AEROMech": ("AIRCRAFT", "MECHANISM"),
    "AEROMil": ("AIRCRAFT", "MILITARY"),
    "AEROMisc": ("AIRCRAFT", "MISC"),
    "AEROProp": ("AIRCRAFT", "PROP"),
    "AERORadio": ("AIRCRAFT", "RADIO CONTROLLED"),
    "AERORckt": ("AIRCRAFT", "ROCKET"),
    "ALRMBell": ("ALARMS", "BELL"),
    "ALRMBuzr": ("ALARMS", "BUZZER"),
    "ALRMClok": ("ALARMS", "CLOCK"),
    "ALRMElec": ("ALARMS", "ELECTRONIC"),
    "ALRMMisc": ("ALARMS", "MISC"),
    "ALRMSirn": ("ALARMS", "SIREN"),
    "AMBAir": ("AMBIENCE", "AIR"),
    "AMBAlpn": ("AMBIENCE", "ALPINE"),
    "AMBAmus": ("AMBIENCE", "AMUSEMENT"),
    "AMBBird": ("AMBIENCE", "BIRDSONG"),
    "AMBCele": ("AMBIENCE", "CELEBRATION"),
    "AMBCnst": ("AMBIENCE", "CONSTRUCTION"),
    "AMBDsrt": ("AMBIENCE", "DESERT"),
    "AMBDsgn": ("AMBIENCE", "DESIGNED"),
    "AMBEmrg": ("AMBIENCE", "EMERGENCY"),
    "AMBFant": ("AMBIENCE", "FANTASY"),
    "AMBFarm": ("AMBIENCE", "FARM"),
    "AMBForst": ("AMBIENCE", "FOREST"),
    "AMBGras": ("AMBIENCE", "GRASSLAND"),
    "AMBHist": ("AMBIENCE", "HISTORICAL"),
    "AMBTech": ("AMBIENCE", "HITECH"),
    "AMBHosp": ("AMBIENCE", "HOSPITAL"),
    "AMBInd": ("AMBIENCE", "INDUSTRIAL"),
    "AMBInsc": ("AMBIENCE", "INSECT"),
    "AMBLake": ("AMBIENCE", "LAKESIDE"),
    "AMBMrkt": ("AMBIENCE", "MARKET"),
    "AMBMisc": ("AMBIENCE", "MISC"),
    "AMBNaut": ("AMBIENCE", "NAUTICAL"),
    "AMBOffc": ("AMBIENCE", "OFFICE"),
    "AMBPark": ("AMBIENCE", "PARK"),
    "AMBPrisn": ("AMBIENCE", "PRISON"),
    "AMBPrtst": ("AMBIENCE", "PROTEST"),
    "AMBPubl": ("AMBIENCE", "PUBLIC PLACE"),
    "AMBRlgn": ("AMBIENCE", "RELIGIOUS"),
    "AMBHome": ("AMBIENCE", "RESIDENTIAL"),
    "AMBRest": ("AMBIENCE", "RESTAURANT & BAR"),
    "AMBRoom": ("AMBIENCE", "ROOM TONE"),
    "AMBRurl": ("AMBIENCE", "RURAL"),
    "AMBSchl": ("AMBIENCE", "SCHOOL"),
    "AMBSci": ("AMBIENCE", "SCIFI"),
    "AMBSea": ("AMBIENCE", "SEASIDE"),
    "AMBSprt": ("AMBIENCE", "SPORT"),
    "AMBSubn": ("AMBIENCE", "SUBURBAN"),
    "AMBSwmp": ("AMBIENCE", "SWAMP"),
    "AMBTown": ("AMBIENCE", "TOWN"),
    "AMBTraf": ("AMBIENCE", "TRAFFIC"),
    "AMBTran": ("AMBIENCE", "TRANSPORTATION"),
    "AMBTrop": ("AMBIENCE", "TROPICAL"),
    "AMBTndra": ("AMBIENCE", "TUNDRA"),
    "AMBUndr": ("AMBIENCE", "UNDERGROUND"),
    "AMBUndwtr": ("AMBIENCE", "UNDERWATER"),
    "AMBUrbn": ("AMBIENCE", "URBAN"),
    "AMBWar": ("AMBIENCE", "WARFARE"),
    "ANMLAmph": ("ANIMALS", "AMPHIBIAN"),
    "ANMLAqua": ("ANIMALS", "AQUATIC"),
    "ANMLBat": ("ANIMALS", "BAT"),
    "ANMLCat": ("ANIMALS", "CAT DOMESTIC"),
    "ANMLWcat": ("ANIMALS", "CAT WILD"),
    "ANMLDog": ("ANIMALS", "DOG"),
    "ANMLWdog": ("ANIMALS", "DOG WILD"),
    "ANMLFarm": ("ANIMALS", "FARM"),
    "ANMLHors": ("ANIMALS", "HORSE"),
    "ANMLInsc": ("ANIMALS", "INSECT"),
    "ANMLMisc": ("ANIMALS", "MISC"),
    "ANMLPrim": ("ANIMALS", "PRIMATE"),
    "ANMLRept": ("ANIMALS", "REPTILE"),
    "ANMLRdnt": ("ANIMALS", "RODENT"),
    "ANMLWild": ("ANIMALS", "WILD"),
    "ADR": ("ARCHIVED", "ADR"),
    "ASSET": ("ARCHIVED", "ASSET"),
    "BNCE": ("ARCHIVED", "BOUNCE"),
    "IR": ("ARCHIVED", "IMPULSE RESPONSE"),
    "LPGRP": ("ARCHIVED", "LOOP GROUP"),
    "MIX": ("ARCHIVED", "MIX"),
    "PFX": ("ARCHIVED", "PFX"),
    "PROD": ("ARCHIVED", "PRODUCTION"),
    "RAW": ("ARCHIVED", "RAW"),
    "REF": ("ARCHIVED", "REFERENCE"),
    "SCNE": ("ARCHIVED", "SCENE"),
    "TEST": ("ARCHIVED", "TEST TONE"),
    "TMARK": ("ARCHIVED", "TRADEMARKED"),
    "WIP": ("ARCHIVED", "WORK IN PROGRESS"),
    "WTF": ("ARCHIVED", "WTF"),
    "BEEPAppl": ("BEEPS", "APPLIANCE"),
    "BEEP": ("BEEPS", "GENERAL"),
    "BEEPLofi": ("BEEPS", "LOFI"),
    "BEEPMed": ("BEEPS", "MEDICAL"),
    "BEEPTimer": ("BEEPS", "TIMER"),
    "BEEPVeh": ("BEEPS", "VEHICLE"),
    "BELLAnml": ("BELLS", "ANIMAL"),
    "BELLDoor": ("BELLS", "DOORBELL"),
    "BELLGong": ("BELLS", "GONG"),
    "BELLHand": ("BELLS", "HANDBELL"),
    "BELLLrg": ("BELLS", "LARGE"),
    "BELLMisc": ("BELLS", "MISC"),
    "BIRDPrey": ("BIRDS", "BIRD OF PREY"),
    "BIRDCrow": ("BIRDS", "CROW"),
    "BIRDFowl": ("BIRDS", "FOWL"),
    "BIRDMisc": ("BIRDS", "MISC"),
    "BIRDSea": ("BIRDS", "SEA"),
    "BIRDSong": ("BIRDS", "SONGBIRD"),
    "BIRDTrop": ("BIRDS", "TROPICAL"),
    "BIRDWade": ("BIRDS", "WADING"),
    "BOATAir": ("BOATS", "AIR BOAT"),
    "BOATWash": ("BOATS", "BOW WASH"),
    "BOATDoor": ("BOATS", "DOOR"),
    "BOATElec": ("BOATS", "ELECTRIC"),
    "BOATFish": ("BOATS", "FISHING"),
    "BOATHorn": ("BOATS", "HORN"),
    "BOATInt": ("BOATS", "INTERIOR"),
    "BOATMech": ("BOATS", "MECHANISM"),
    "BOATMil": ("BOATS", "MILITARY"),
    "BOATMisc": ("BOATS", "MISC"),
    "BOATMotr": ("BOATS", "MOTORBOAT"),
    "BOATRace": ("BOATS", "RACING"),
    "BOATRow": ("BOATS", "ROWBOAT"),
    "BOATSail": ("BOATS", "SAILBOAT"),
    "BOATShip": ("BOATS", "SHIP"),
    "BOATStm": ("BOATS", "STEAM"),
    "BOATSub": ("BOATS", "SUBMARINE"),
    "BOATUndwtr": ("BOATS", "UNDERWATER"),
    "BLLTBy": ("BULLETS", "BY"),
    "BLLTImpt": ("BULLETS", "IMPACT"),
    "BLLTMisc": ("BULLETS", "MISC"),
    "BLLTRico": ("BULLETS", "RICOCHET"),
    "BLLTShel": ("BULLETS", "SHELL"),
    "TOONAnml": ("CARTOON", "ANIMAL"),
    "TOONBoing": ("CARTOON", "BOING"),
    "TOONClang": ("CARTOON", "CLANG"),
    "TOONCreak": ("CARTOON", "CREAK"),
    "TOONHorn": ("CARTOON", "HORN"),
    "TOONImpt": ("CARTOON", "IMPACT"),
    "TOONMach": ("CARTOON", "MACHINE"),
    "TOONMisc": ("CARTOON", "MISC"),
    "TOONMx": ("CARTOON", "MUSICAL"),
    "TOONPluk": ("CARTOON", "PLUCK"),
    "TOONPop": ("CARTOON", "POP"),
    "TOONShake": ("CARTOON", "SHAKE"),
    "TOONSplt": ("CARTOON", "SPLAT"),
    "TOONSqk": ("CARTOON", "SQUEAK"),
    "TOONStrch": ("CARTOON", "STRETCH"),
    "TOONSwsh": ("CARTOON", "SWISH"),
    "TOONTwang": ("CARTOON", "TWANG"),
    "TOONVeh": ("CARTOON", "VEHICLE"),
    "TOONVox": ("CARTOON", "VOCAL"),
    "TOONWarb": ("CARTOON", "WARBLE"),
    "TOONWhis": ("CARTOON", "WHISTLE"),
    "TOONZip": ("CARTOON", "ZIP"),
    "CERMBrk": ("CERAMICS", "BREAK"),
    "CERMCrsh": ("CERAMICS", "CRASH & DEBRIS"),
    "CERMFric": ("CERAMICS", "FRICTION"),
    "CERMHndl": ("CERAMICS", "HANDLE"),
    "CERMImpt": ("CERAMICS", "IMPACT"),
    "CERMMisc": ("CERAMICS", "MISC"),
    "CERMMvmt": ("CERAMICS", "MOVEMENT"),
    "CERMTonl": ("CERAMICS", "TONAL"),
    "CHAINBrk": ("CHAINS", "BREAK"),
    "CHAINHndl": ("CHAINS", "HANDLE"),
    "CHAINImpt": ("CHAINS", "IMPACT"),
    "CHAINMisc": ("CHAINS", "MISC"),
    "CHAINMvmt": ("CHAINS", "MOVEMENT"),
    "CHEMAcid": ("CHEMICALS", "ACID"),
    "CHEMMisc": ("CHEMICALS", "MISC"),
    "CHEMReac": ("CHEMICALS", "REACTION"),
    "CLOCKChim": ("CLOCKS", "CHIME"),
    "CLOCKMech": ("CLOCKS", "MECHANICS"),
    "CLOCKMisc": ("CLOCKS", "MISC"),
    "CLOCKTick": ("CLOCKS", "TICK"),
    "CLOTHFlp": ("CLOTH", "FLAP"),
    "CLOTHHndl": ("CLOTH", "HANDLE"),
    "CLOTHImpt": ("CLOTH", "IMPACT"),
    "CLOTHMisc": ("CLOTH", "MISC"),
    "CLOTHMvmt": ("CLOTH", "MOVEMENT"),
    "CLOTHRip": ("CLOTH", "RIP"),
    "COMAv": ("COMMUNICATIONS", "AUDIO VISUAL"),
    "COMCam": ("COMMUNICATIONS", "CAMERA"),
    "COMCell": ("COMMUNICATIONS", "CELLPHONE"),
    "COMMic": ("COMMUNICATIONS", "MICROPHONE"),
    "COMMisc": ("COMMUNICATIONS", "MISC"),
    "COMPhono": ("COMMUNICATIONS", "PHONOGRAPH"),
    "COMRadio": ("COMMUNICATIONS", "RADIO"),
    "COMStatic": ("COMMUNICATIONS", "STATIC"),
    "COMTelm": ("COMMUNICATIONS", "TELEMETRY"),
    "COMTelph": ("COMMUNICATIONS", "TELEPHONE"),
    "COMTv": ("COMMUNICATIONS", "TELEVISION"),
    "COMTran": ("COMMUNICATIONS", "TRANSCEIVER"),
    "COMType": ("COMMUNICATIONS", "TYPEWRITER"),
    "CMPTDriv": ("COMPUTERS", "HARD DRIVE"),
    "CMPTKey": ("COMPUTERS", "KEYBOARD & MOUSE"),
    "CMPTMisc": ("COMPUTERS", "MISC"),
    "CREAAqua": ("CREATURES", "AQUATIC"),
    "CREAAvian": ("CREATURES", "AVIAN"),
    "CREABeast": ("CREATURES", "BEAST"),
    "CREABlob": ("CREATURES", "BLOB"),
    "CREADino": ("CREATURES", "DINOSAUR"),
    "CREADrgn": ("CREATURES", "DRAGON"),
    "CREAElem": ("CREATURES", "ELEMENTAL"),
    "CREAEthr": ("CREATURES", "ETHEREAL"),
    "CREAHmn": ("CREATURES", "HUMANOID"),
    "CREAInsc": ("CREATURES", "INSECTOID"),
    "CREAMisc": ("CREATURES", "MISC"),
    "CREAMnstr": ("CREATURES", "MONSTER"),
    "CREARept": ("CREATURES", "REPTILIAN"),
    "CREASmall": ("CREATURES", "SMALL"),
    "CREASrce": ("CREATURES", "SOURCE"),
    "CRWDAngr": ("CROWDS", "ANGRY"),
    "CRWDApls": ("CROWDS", "APPLAUSE"),
    "CRWDBatl": ("CROWDS", "BATTLE"),
    "CRWDCele": ("CROWDS", "CELEBRATION"),
    "CRWDCheer": ("CROWDS", "CHEERING"),
    "CRWDChld": ("CROWDS", "CHILDREN"),
    "CRWDConv": ("CROWDS", "CONVERSATION"),
    "CRWDLaff": ("CROWDS", "LAUGHTER"),
    "CRWDLoop": ("CROWDS", "LOOP GROUP"),
    "CRWDMisc": ("CROWDS", "MISC"),
    "CRWDPanic": ("CROWDS", "PANIC"),
    "CRWDQuiet": ("CROWDS", "QUIET"),
    "CRWDReac": ("CROWDS", "REACTION"),
    "CRWDSing": ("CROWDS", "SINGING"),
    "CRWDSprt": ("CROWDS", "SPORT"),
    "CRWDWalla": ("CROWDS", "WALLA"),
    "DSGNBass": ("DESIGNED", "BASS DIVE"),
    "DSGNBoom": ("DESIGNED", "BOOM"),
    "DSGNBram": ("DESIGNED", "BRAAM"),
    "DSGNDist": ("DESIGNED", "DISTORTION"),
    "DSGNDron": ("DESIGNED", "DRONE"),
    "DSGNErie": ("DESIGNED", "EERIE"),
    "DSGNEthr": ("DESIGNED", "ETHEREAL"),
    "DSGNGran": ("DESIGNED", "GRANULAR"),
    "DSGNImpt": ("DESIGNED", "IMPACT"),
    "DSGNMisc": ("DESIGNED", "MISC"),
    "DSGNMorph": ("DESIGNED", "MORPH"),
    "DSGNRise": ("DESIGNED", "RISER"),
    "DSGNRmbl": ("DESIGNED", "RUMBLE"),
    "DSGNRythm": ("DESIGNED", "RHYTHMIC"),
    "DSGNSrce": ("DESIGNED", "SOURCE"),
    "DSGNStngr": ("DESIGNED", "STINGER"),
    "DSGNSynth": ("DESIGNED", "SYNTHETIC"),
    "DSGNTonl": ("DESIGNED", "TONAL"),
    "DSGNVocl": ("DESIGNED", "VOCAL"),
    "DSGNWhsh": ("DESIGNED", "WHOOSH"),
    "DESTRClpse": ("DESTRUCTION", "COLLAPSE"),
    "DESTRCrsh": ("DESTRUCTION", "CRASH & DEBRIS"),
    "DESTRMisc": ("DESTRUCTION", "MISC"),
    "DIRTCrsh": ("DIRT & SAND", "CRASH & DEBRIS"),
    "DIRTDust": ("DIRT & SAND", "DUST"),
    "DIRTHndl": ("DIRT & SAND", "HANDLE"),
    "DIRTImpt": ("DIRT & SAND", "IMPACT"),
    "DIRTMisc": ("DIRT & SAND", "MISC"),
    "DIRTMvmt": ("DIRT & SAND", "MOVEMENT"),
    "DIRTTonl": ("DIRT & SAND", "TONAL"),
    "DOORAntq": ("DOORS", "ANTIQUE"),
    "DOORAppl": ("DOORS", "APPLIANCE"),
    "DOORCab": ("DOORS", "CABINET"),
    "DOORComp": ("DOORS", "COMPOSITE"),
    "DOORCreak": ("DOORS", "CREAK"),
    "DOORDungn": ("DOORS", "DUNGEON"),
    "DOORElec": ("DOORS", "ELECTRIC"),
    "DOORGate": ("DOORS", "GATE"),
    "DOORGlas": ("DOORS", "GLASS"),
    "DOORHdwr": ("DOORS", "HARDWARE"),
    "DOORTech": ("DOORS", "HITECH"),
    "DOORHydr": ("DOORS", "HYDRAULIC & PNEUMATIC"),
    "DOORKnck": ("DOORS", "KNOCK"),
    "DOORMetl": ("DOORS", "METAL"),
    "DOORMisc": ("DOORS", "MISC"),
    "DOORPlas": ("DOORS", "PLASTIC"),
    "DOORPrisn": ("DOORS", "PRISON"),
    "DOORRevl": ("DOORS", "REVOLVING"),
    "DOORSlid": ("DOORS", "SLIDING"),
    "DOORSton": ("DOORS", "STONE"),
    "DOORSwng": ("DOORS", "SWINGING"),
    "DOORWood": ("DOORS", "WOOD"),
    "DRWRMetl": ("DRAWERS", "METAL"),
    "DRWRMisc": ("DRAWERS", "MISC"),
    "DRWRPlas": ("DRAWERS", "PLASTIC"),
    "DRWRWood": ("DRAWERS", "WOOD"),
    "ELECArc": ("ELECTRICITY", "ARC"),
    "ELECBuzz": ("ELECTRICITY", "BUZZ & HUM"),
    "ELECEmf": ("ELECTRICITY", "ELECTROMAGNETIC"),
    "ELECMisc": ("ELECTRICITY", "MISC"),
    "ELECSprk": ("ELECTRICITY", "SPARKS"),
    "ELECZap": ("ELECTRICITY", "ZAP"),
    "EQUIPBridle": ("EQUIPMENT", "BRIDLE & TACK"),
    "EQUIPTech": ("EQUIPMENT", "HITECH"),
    "EQUIPMisc": ("EQUIPMENT", "MISC"),
    "EQUIPRec": ("EQUIPMENT", "RECREATIONAL"),
    "EQUIPSprt": ("EQUIPMENT", "SPORT"),
    "EQUIPTact": ("EQUIPMENT", "TACTICAL"),
    "EXPLDsgn": ("EXPLOSIONS", "DESIGNED"),
    "EXPLMisc": ("EXPLOSIONS", "MISC"),
    "EXPLReal": ("EXPLOSIONS", "REAL"),
    "FARTDsgn": ("FARTS", "DESIGNED"),
    "FARTMisc": ("FARTS", "MISC"),
    "FARTReal": ("FARTS", "REAL"),
    "FGHTBf": ("FIGHT", "BODYFALL"),
    "FGHTClth": ("FIGHT", "CLOTH"),
    "FGHTGrab": ("FIGHT", "GRAB"),
    "FGHTImpt": ("FIGHT", "IMPACT"),
    "FGHTMisc": ("FIGHT", "MISC"),
    "FIREBurn": ("FIRE", "BURNING"),
    "FIREBrst": ("FIRE", "BURST"),
    "FIRECrkl": ("FIRE", "CRACKLE"),
    "FIREGas": ("FIRE", "GAS"),
    "FIREIgn": ("FIRE", "IGNITE"),
    "FIREMisc": ("FIRE", "MISC"),
    "FIRESizz": ("FIRE", "SIZZLE"),
    "FIRETrch": ("FIRE", "TORCH"),
    "FIRETurb": ("FIRE", "TURBULENT"),
    "FIREWhsh": ("FIRE", "WHOOSH"),
    "FRWKComr": ("FIREWORKS", "COMMERCIAL"),
    "FRWKMisc": ("FIREWORKS", "MISC"),
    "FRWKRec": ("FIREWORKS", "RECREATIONAL"),
    "FOLYClth": ("FOLEY", "CLOTH"),
    "FOLYFeet": ("FOLEY", "FEET"),
    "FOLYHand": ("FOLEY", "HANDS"),
    "FOLYMisc": ("FOLEY", "MISC"),
    "FOLYProp": ("FOLEY", "PROP"),
    "FOODCook": ("FOOD & DRINK", "COOKING"),
    "FOODDrnk": ("FOOD & DRINK", "DRINKING"),
    "FOODEat": ("FOOD & DRINK", "EATING"),
    "FOODGware": ("FOOD & DRINK", "GLASSWARE"),
    "FOODIngr": ("FOOD & DRINK", "INGREDIENTS"),
    "FOODKware": ("FOOD & DRINK", "KITCHENWARE"),
    "FOODMisc": ("FOOD & DRINK", "MISC"),
    "FOODPour": ("FOOD & DRINK", "POUR"),
    "FOODTware": ("FOOD & DRINK", "TABLEWARE"),
    "FEETAnml": ("FOOTSTEPS", "ANIMAL"),
    "FEETCrea": ("FOOTSTEPS", "CREATURE"),
    "FEETHors": ("FOOTSTEPS", "HORSE"),
    "FEETHmn": ("FOOTSTEPS", "HUMAN"),
    "FEETMisc": ("FOOTSTEPS", "MISC"),
    "GAMEArcd": ("GAMES", "ARCADE"),
    "GAMEBoard": ("GAMES", "BOARD"),
    "GAMECas": ("GAMES", "CASINO"),
    "GAMEMisc": ("GAMES", "MISC"),
    "GAMEVideo": ("GAMES", "VIDEO"),
    "GEOFuma": ("GEOTHERMAL", "FUMAROLE"),
    "GEOGeyser": ("GEOTHERMAL", "GEYSER"),
    "GEOLava": ("GEOTHERMAL", "LAVA"),
    "GEOMisc": ("GEOTHERMAL", "MISC"),
    "GEOMudpot": ("GEOTHERMAL", "MUD POTS"),
    "GLASBrk": ("GLASS", "BREAK"),
    "GLASCrsh": ("GLASS", "CRASH & DEBRIS"),
    "GLASFric": ("GLASS", "FRICTION"),
    "GLASHndl": ("GLASS", "HANDLE"),
    "GLASImpt": ("GLASS", "IMPACT"),
    "GLASMisc": ("GLASS", "MISC"),
    "GLASMvmt": ("GLASS", "MOVEMENT"),
    "GLASTonl": ("GLASS", "TONAL"),
    "GOREBlood": ("GORE", "BLOOD"),
    "GOREBone": ("GORE", "BONE"),
    "GOREBurn": ("GORE", "BURN"),
    "GOREFlsh": ("GORE", "FLESH"),
    "GOREMisc": ("GORE", "MISC"),
    "GOREOoze": ("GORE", "OOZE"),
    "GORESrce": ("GORE", "SOURCE"),
    "GORESplt": ("GORE", "SPLAT"),
    "GORESqsh": ("GORE", "SQUISH"),
    "GOREStab": ("GORE", "STAB"),
    "GUNAntq": ("GUNS", "ANTIQUE"),
    "GUNArtl": ("GUNS", "ARTILLERY"),
    "GUNAuto": ("GUNS", "AUTOMATIC"),
    "GUNCano": ("GUNS", "CANNON"),
    "GUNHndl": ("GUNS", "HANDLE"),
    "GUNTech": ("GUNS", "HITECH"),
    "GUNMech": ("GUNS", "MECHANISM"),
    "GUNMisc": ("GUNS", "MISC"),
    "GUNPis": ("GUNS", "PISTOL"),
    "GUNRif": ("GUNS", "RIFLE"),
    "GUNShotg": ("GUNS", "SHOTGUN"),
    "GUNSupr": ("GUNS", "SUPPRESSED"),
    "HORNAir": ("HORNS", "AIR POWERED"),
    "HORNCele": ("HORNS", "CELEBRATION"),
    "HORNMisc": ("HORNS", "MISC"),
    "HORNTrad": ("HORNS", "TRADITIONAL"),
    "HMNBlow": ("HUMAN", "BLOW"),
    "HMNBrth": ("HUMAN", "BREATH"),
    "HMNBurp": ("HUMAN", "BURP"),
    "HMNCough": ("HUMAN", "COUGH"),
    "HMNHart": ("HUMAN", "HEARTBEAT"),
    "HMNKiss": ("HUMAN", "KISS"),
    "HMNMisc": ("HUMAN", "MISC"),
    "HMNPee": ("HUMAN", "PEE"),
    "HMNSkin": ("HUMAN", "SKIN"),
    "HMNSneez": ("HUMAN", "SNEEZE"),
    "HMNSniff": ("HUMAN", "SNIFF"),
    "HMNSnor": ("HUMAN", "SNORE"),
    "HMNSpit": ("HUMAN", "SPIT"),
    "HMNVomit": ("HUMAN", "VOMIT"),
    "ICEBrk": ("ICE", "BREAK"),
    "ICECrsh": ("ICE", "CRASH & DEBRIS"),
    "ICEFric": ("ICE", "FRICTION"),
    "ICEHndl": ("ICE", "HANDLE"),
    "ICEImpt": ("ICE", "IMPACT"),
    "ICEMisc": ("ICE", "MISC"),
    "ICEMvmt": ("ICE", "MOVEMENT"),
    "ICETonl": ("ICE", "TONAL"),
    "LASRBeam": ("LASERS", "BEAM"),
    "LASRGun": ("LASERS", "GUN"),
    "LASRImpt": ("LASERS", "IMPACT"),
    "LASRMisc": ("LASERS", "MISC"),
    "LETHRCreak": ("LEATHER", "CREAK"),
    "LETHRHndl": ("LEATHER", "HANDLE"),
    "LETHRImpt": ("LEATHER", "IMPACT"),
    "LETHRMisc": ("LEATHER", "MISC"),
    "LETHRMvmt": ("LEATHER", "MOVEMENT"),
    "LIQBubl": ("LIQUID & MUD", "BUBBLES"),
    "LIQImpt": ("LIQUID & MUD", "IMPACT"),
    "LIQMisc": ("LIQUID & MUD", "MISC"),
    "LIQMvmt": ("LIQUID & MUD", "MOVEMENT"),
    "LIQSuct": ("LIQUID & MUD", "SUCTION"),
    "MACHAmus": ("MACHINES", "AMUSEMENT"),
    "MACHAntq": ("MACHINES", "ANTIQUE"),
    "MACHAppl": ("MACHINES", "APPLIANCE"),
    "MACHCnst": ("MACHINES", "CONSTRUCTION"),
    "MACHElev": ("MACHINES", "ELEVATOR"),
    "MACHEscl": ("MACHINES", "ESCALATOR"),
    "MACHFan": ("MACHINES", "FAN"),
    "MACHGrdn": ("MACHINES", "GARDEN"),
    "MACHGym": ("MACHINES", "GYM"),
    "MACHTech": ("MACHINES", "HITECH"),
    "MACHHvac": ("MACHINES", "HVAC"),
    "MACHInd": ("MACHINES", "INDUSTRIAL"),
    "MACHMech": ("MACHINES", "MECHANISM"),
    "MACHMed": ("MACHINES", "MEDICAL"),
    "MACHMisc": ("MACHINES", "MISC"),
    "MACHOffc": ("MACHINES", "OFFICE"),
    "MACHPump": ("MACHINES", "PUMP"),
    "MAGAngl": ("MAGIC", "ANGELIC"),
    "MAGElem": ("MAGIC", "ELEMENTAL"),
    "MAGEvil": ("MAGIC", "EVIL"),
    "MAGMisc": ("MAGIC", "MISC"),
    "MAGPoof": ("MAGIC", "POOF"),
    "MAGShim": ("MAGIC", "SHIMMER"),
    "MAGSpel": ("MAGIC", "SPELL"),
    "MECHClik": ("MECHANICAL", "CLICK"),
    "MECHGear": ("MECHANICAL", "GEARS"),
    "MECHHydr": ("MECHANICAL", "HYDRAULIC & PNEUMATIC"),
    "MECHLtch": ("MECHANICAL", "LATCH"),
    "MECHLvr": ("MECHANICAL", "LEVER"),
    "MECHLock": ("MECHANICAL", "LOCK"),
    "MECHMisc": ("MECHANICAL", "MISC"),
    "MECHPuly": ("MECHANICAL", "PULLEY"),
    "MECHRtch": ("MECHANICAL", "RATCHET"),
    "MECHRelay": ("MECHANICAL", "RELAY"),
    "MECHRolr": ("MECHANICAL", "ROLLER"),
    "MECHSwtch": ("MECHANICAL", "SWITCH"),
    "METLBrk": ("METAL", "BREAK"),
    "METLCrsh": ("METAL", "CRASH & DEBRIS"),
    "METLFric": ("METAL", "FRICTION"),
    "METLHndl": ("METAL", "HANDLE"),
    "METLImpt": ("METAL", "IMPACT"),
    "METLMisc": ("METAL", "MISC"),
    "METLMvmt": ("METAL", "MOVEMENT"),
    "METLTonl": ("METAL", "TONAL"),
    "MOTRAntq": ("MOTORS", "ANTIQUE"),
    "MOTRComb": ("MOTORS", "COMBUSTION"),
    "MOTRElec": ("MOTORS", "ELECTRIC"),
    "MOTRMisc": ("MOTORS", "MISC"),
    "MOTRSrvo": ("MOTORS", "SERVO"),
    "MOTRTurb": ("MOTORS", "TURBINE"),
    "MOVEActv": ("MOVEMENT", "ACTIVITY"),
    "MOVEAnml": ("MOVEMENT", "ANIMAL"),
    "MOVECrea": ("MOVEMENT", "CREATURE"),
    "MOVECrwd": ("MOVEMENT", "CROWD"),
    "MOVEHmn": ("MOVEMENT", "HUMAN"),
    "MOVEInsc": ("MOVEMENT", "INSECT"),
    "MOVEMisc": ("MOVEMENT", "MISC"),
    "MOVEPres": ("MOVEMENT", "PRESENCE"),
    "MUSCBell": ("MUSICAL", "BELLS"),
    "MUSCBrass": ("MUSICAL", "BRASS"),
    "MUSCChim": ("MUSICAL", "CHIME"),
    "MUSCChor": ("MUSICAL", "CHORAL"),
    "MUSCExpr": ("MUSICAL", "EXPERIMENTAL"),
    "MUSCInst": ("MUSICAL", "INSTRUMENT"),
    "MUSCKeyd": ("MUSICAL", "KEYED"),
    "MUSCLoop": ("MUSICAL", "LOOP"),
    "MUSCMisc": ("MUSICAL", "MISC"),
    "MUSCPerc": ("MUSICAL", "PERCUSSION"),
    "MUSCTnprc": ("MUSICAL", "PERCUSSION TUNED"),
    "MUSCPrfm": ("MUSICAL", "PERFORMANCE"),
    "MUSCPluck": ("MUSICAL", "PLUCKED"),
    "MUSCSmpl": ("MUSICAL", "SAMPLE"),
    "MUSCShake": ("MUSICAL", "SHAKEN"),
    "MUSCSong": ("MUSICAL", "SONG & PHRASE"),
    "MUSCStngr": ("MUSICAL", "STINGER"),
    "MUSCStr": ("MUSICAL", "STRINGED"),
    "MUSCSynth": ("MUSICAL", "SYNTHESIZED"),
    "MUSCToy": ("MUSICAL", "TOY"),
    "MUSCWind": ("MUSICAL", "WOODWIND"),
    "NATDAval": ("NATURAL DISASTER", "AVALANCHE"),
    "NATDQuak": ("NATURAL DISASTER", "EARTHQUAKE"),
    "NATDMisc": ("NATURAL DISASTER", "MISC"),
    "NATDTorn": ("NATURAL DISASTER", "TORNADO"),
    "NATDTsun": ("NATURAL DISASTER", "TSUNAMI"),
    "NATDThyp": ("NATURAL DISASTER", "TYPHOON"),
    "NATDVolc": ("NATURAL DISASTER", "VOLCANO"),
    "OBJBag": ("OBJECTS", "BAG"),
    "OBJBook": ("OBJECTS", "BOOK"),
    "OBJCoin": ("OBJECTS", "COIN"),
    "OBJCont": ("OBJECTS", "CONTAINER"),
    "OBJFash": ("OBJECTS", "FASHION"),
    "OBJFurn": ("OBJECTS", "FURNITURE"),
    "OBJGrdn": ("OBJECTS", "GARDEN"),
    "OBJGym": ("OBJECTS", "GYM"),
    "OBJHsehld": ("OBJECTS", "HOUSEHOLD"),
    "OBJJewl": ("OBJECTS", "JEWELRY"),
    "OBJKey": ("OBJECTS", "KEYS"),
    "OBJLug": ("OBJECTS", "LUGGAGE"),
    "OBJMed": ("OBJECTS", "MEDICAL"),
    "OBJMisc": ("OBJECTS", "MISC"),
    "OBJOffc": ("OBJECTS", "OFFICE"),
    "OBJPack": ("OBJECTS", "PACKAGING"),
    "OBJTape": ("OBJECTS", "TAPE"),
    "OBJUmbr": ("OBJECTS", "UMBRELLA"),
    "OBJWhled": ("OBJECTS", "WHEELED"),
    "OBJWrite": ("OBJECTS", "WRITING"),
    "OBJZipr": ("OBJECTS", "ZIPPER"),
    "PAPRFltr": ("PAPER", "FLUTTER"),
    "PAPRFric": ("PAPER", "FRICTION"),
    "PAPRHndl": ("PAPER", "HANDLE"),
    "PAPRImpt": ("PAPER", "IMPACT"),
    "PAPRMisc": ("PAPER", "MISC"),
    "PAPRRip": ("PAPER", "RIP"),
    "PAPRTonl": ("PAPER", "TONAL"),
    "PLASBrk": ("PLASTIC", "BREAK"),
    "PLASCrsh": ("PLASTIC", "CRASH & DEBRIS"),
    "PLASFric": ("PLASTIC", "FRICTION"),
    "PLASHndl": ("PLASTIC", "HANDLE"),
    "PLASImpt": ("PLASTIC", "IMPACT"),
    "PLASMisc": ("PLASTIC", "MISC"),
    "PLASMvmt": ("PLASTIC", "MOVEMENT"),
    "PLASTonl": ("PLASTIC", "TONAL"),
    "RAINClth": ("RAIN", "CLOTH"),
    "RAINConc": ("RAIN", "CONCRETE"),
    "RAIN": ("RAIN", "GENERAL"),
    "RAINGlas": ("RAIN", "GLASS"),
    "RAINInt": ("RAIN", "INTERIOR"),
    "RAINMetl": ("RAIN", "METAL"),
    "RAINPlas": ("RAIN", "PLASTIC"),
    "RAINVege": ("RAIN", "VEGETATION"),
    "RAINWatr": ("RAIN", "WATER"),
    "RAINWood": ("RAIN", "WOOD"),
    "ROBTMisc": ("ROBOTS", "MISC"),
    "ROBTMvmt": ("ROBOTS", "MOVEMENT"),
    "ROBTVox": ("ROBOTS", "VOCAL"),
    "ROCKBrk": ("ROCKS", "BREAK"),
    "ROCKCrsh": ("ROCKS", "CRASH & DEBRIS"),
    "ROCKFric": ("ROCKS", "FRICTION"),
    "ROCKHndl": ("ROCKS", "HANDLE"),
    "ROCKImpt": ("ROCKS", "IMPACT"),
    "ROCKMisc": ("ROCKS", "MISC"),
    "ROCKMvmt": ("ROCKS", "MOVEMENT"),
    "ROCKTonl": ("ROCKS", "TONAL"),
    "ROPECreak": ("ROPE", "CREAK"),
    "ROPEHndl": ("ROPE", "HANDLE"),
    "ROPEImpt": ("ROPE", "IMPACT"),
    "ROPEMisc": ("ROPE", "MISC"),
    "ROPEMvmt": ("ROPE", "MOVEMENT"),
    "RUBRCrsh": ("RUBBER", "CRASH & DEBRIS"),
    "RUBRFric": ("RUBBER", "FRICTION"),
    "RUBRHndl": ("RUBBER", "HANDLE"),
    "RUBRImpt": ("RUBBER", "IMPACT"),
    "RUBRMisc": ("RUBBER", "MISC"),
    "RUBRMvmt": ("RUBBER", "MOVEMENT"),
    "RUBRTonl": ("RUBBER", "TONAL"),
    "SCIAlrm": ("SCIFI", "ALARM"),
    "SCICmpt": ("SCIFI", "COMPUTER"),
    "SCIDoor": ("SCIFI", "DOOR"),
    "SCIEnrg": ("SCIFI", "ENERGY"),
    "SCIImpt": ("SCIFI", "IMPACT"),
    "SCIMach": ("SCIFI", "MACHINE"),
    "SCIMech": ("SCIFI", "MECHANISM"),
    "SCIMisc": ("SCIFI", "MISC"),
    "SCIRetro": ("SCIFI", "RETRO"),
    "SCIShip": ("SCIFI", "SPACESHIP"),
    "SCIVeh": ("SCIFI", "VEHICLE"),
    "SCIWeap": ("SCIFI", "WEAPON"),
    "SNOWCrsh": ("SNOW", "CRASH & DEBRIS"),
    "SNOWFric": ("SNOW", "FRICTION"),
    "SNOWHndl": ("SNOW", "HANDLE"),
    "SNOWImpt": ("SNOW", "IMPACT"),
    "SNOWMisc": ("SNOW", "MISC"),
    "SNOWMvmt": ("SNOW", "MOVEMENT"),
    "SPRTCourt": ("SPORTS", "COURT"),
    "SPRTField": ("SPORTS", "FIELD"),
    "SPRTGym": ("SPORTS", "GYM"),
    "SPRTIndor": ("SPORTS", "INDOOR"),
    "SPRTMisc": ("SPORTS", "MISC"),
    "SPRTSkate": ("SPORTS", "SKATE"),
    "SPRTTrck": ("SPORTS", "TRACK & FIELD"),
    "SPRTWatr": ("SPORTS", "WATER"),
    "SPRTWntr": ("SPORTS", "WINTER"),
    "SWSH": ("SWOOSHES", "SWISH"),
    "WHSH": ("SWOOSHES", "WHOOSH"),
    "TOOLGrdn": ("TOOLS", "GARDEN"),
    "TOOLHand": ("TOOLS", "HAND"),
    "TOOLMisc": ("TOOLS", "MISC"),
    "TOOLPneu": ("TOOLS", "PNEUMATIC"),
    "TOOLPowr": ("TOOLS", "POWER"),
    "TOYElec": ("TOYS", "ELECTRONIC"),
    "TOYMech": ("TOYS", "MECHANICAL"),
    "TOYMisc": ("TOYS", "MISC"),
    "TRNBrake": ("TRAINS", "BRAKE"),
    "TRNClak": ("TRAINS", "CLACK"),
    "TRNDoor": ("TRAINS", "DOOR"),
    "TRNDiesl": ("TRAINS", "DIESEL"),
    "TRNElec": ("TRAINS", "ELECTRIC"),
    "TRNHspd": ("TRAINS", "HIGH SPEED"),
    "TRNHorn": ("TRAINS", "HORN"),
    "TRNInt": ("TRAINS", "INTERIOR"),
    "TRNMech": ("TRAINS", "MECHANISM"),
    "TRNMisc": ("TRAINS", "MISC"),
    "TRNSteam": ("TRAINS", "STEAM"),
    "TRNSbwy": ("TRAINS", "SUBWAY"),
    "TRNTram": ("TRAINS", "TRAM"),
    "UIAlert": ("USER INTERFACE", "ALERT"),
    "UIBeep": ("USER INTERFACE", "BEEP"),
    "UIClick": ("USER INTERFACE", "CLICK"),
    "UIData": ("USER INTERFACE", "DATA"),
    "UIGlitch": ("USER INTERFACE", "GLITCH"),
    "UIMisc": ("USER INTERFACE", "MISC"),
    "UIMvmt": ("USER INTERFACE", "MOTION"),
    "VEGEGras": ("VEGETATION", "GRASS"),
    "VEGELeaf": ("VEGETATION", "LEAVES"),
    "VEGEMisc": ("VEGETATION", "MISC"),
    "VEGETree": ("VEGETATION", "TREE"),
    "VEHAlrm": ("VEHICLES", "ALARM"),
    "VEHAntq": ("VEHICLES", "ANTIQUE"),
    "VEHAtv": ("VEHICLES", "ATV"),
    "VEHBike": ("VEHICLES", "BICYCLE"),
    "VEHBrake": ("VEHICLES", "BRAKE"),
    "VEHBus": ("VEHICLES", "BUS"),
    "VEHCar": ("VEHICLES", "CAR"),
    "VEHCnst": ("VEHICLES", "CONSTRUCTION"),
    "VEHDoor": ("VEHICLES", "DOOR"),
    "VEHElec": ("VEHICLES", "ELECTRIC"),
    "VEHEmrg": ("VEHICLES", "EMERGENCY"),
    "VEHFarm": ("VEHICLES", "FARM"),
    "VEHFrght": ("VEHICLES", "FREIGHT"),
    "VEHBy": ("VEHICLES", "GENERIC BY"),
    "VEHHorn": ("VEHICLES", "HORN"),
    "VEHInt": ("VEHICLES", "INTERIOR"),
    "VEHJalop": ("VEHICLES", "JALOPY"),
    "VEHMech": ("VEHICLES", "MECHANISM"),
    "VEHMil": ("VEHICLES", "MILITARY"),
    "VEHMisc": ("VEHICLES", "MISC"),
    "VEHMoto": ("VEHICLES", "MOTORCYCLE"),
    "VEHRace": ("VEHICLES", "RACING"),
    "VEHSirn": ("VEHICLES", "SIREN"),
    "VEHSkid": ("VEHICLES", "SKID"),
    "VEHSusp": ("VEHICLES", "SUSPENSION"),
    "VEHTire": ("VEHICLES", "TIRE"),
    "VEHTruck": ("VEHICLES", "TRUCK VAN & SUV"),
    "VEHUtil": ("VEHICLES", "UTILITY"),
    "VEHWagn": ("VEHICLES", "WAGON"),
    "VEHWndw": ("VEHICLES", "WINDOW"),
    "VOXAlien": ("VOICES", "ALIEN"),
    "VOXBaby": ("VOICES", "BABY"),
    "VOXCheer": ("VOICES", "CHEER"),
    "VOXChld": ("VOICES", "CHILD"),
    "VOXCry": ("VOICES", "CRYING"),
    "VOXEfrt": ("VOICES", "EFFORTS"),
    "VOXFem": ("VOICES", "FEMALE"),
    "VOXFutz": ("VOICES", "FUTZED"),
    "VOXHist": ("VOICES", "HISTORICAL"),
    "VOXLaff": ("VOICES", "LAUGH"),
    "VOXMale": ("VOICES", "MALE"),
    "VOXMisc": ("VOICES", "MISC"),
    "VOXReac": ("VOICES", "REACTION"),
    "VOXScrm": ("VOICES", "SCREAM"),
    "VOXSing": ("VOICES", "SINGING"),
    "VOXWhsp": ("VOICES", "WHISPER"),
    "WATRBubl": ("WATER", "BUBBLES"),
    "WATRDran": ("WATER", "DRAIN"),
    "WATRDrip": ("WATER", "DRIP"),
    "WATRFizz": ("WATER", "FIZZ"),
    "WATRFlow": ("WATER", "FLOW"),
    "WATRFoun": ("WATER", "FOUNTAIN"),
    "WATRImpt": ("WATER", "IMPACT"),
    "WATRLap": ("WATER", "LAP"),
    "WATRMisc": ("WATER", "MISC"),
    "WATRMvmt": ("WATER", "MOVEMENT"),
    "WATRPlmb": ("WATER", "PLUMBING"),
    "WATRPour": ("WATER", "POUR"),
    "WATRSplsh": ("WATER", "SPLASH"),
    "WATRSpray": ("WATER", "SPRAY"),
    "WATRStm": ("WATER", "STEAM"),
    "WATRSurf": ("WATER", "SURF"),
    "WATRTurb": ("WATER", "TURBULENT"),
    "WATRUndwtr": ("WATER", "UNDERWATER"),
    "WATRFall": ("WATER", "WATERFALL"),
    "WATRWave": ("WATER", "WAVE"),
    "WEAPArmr": ("WEAPONS", "ARMOR"),
    "WEAPArro": ("WEAPONS", "ARROW"),
    "WEAPAxe": ("WEAPONS", "AXE"),
    "WEAPBlnt": ("WEAPONS", "BLUNT"),
    "WEAPBow": ("WEAPONS", "BOW"),
    "WEAPKnif": ("WEAPONS", "KNIFE"),
    "WEAPMisc": ("WEAPONS", "MISC"),
    "WEAPPole": ("WEAPONS", "POLEARM"),
    "WEAPSiege": ("WEAPONS", "SIEGE"),
    "WEAPSwrd": ("WEAPONS", "SWORD"),
    "WEAPWhip": ("WEAPONS", "WHIP"),
    "HAIL": ("WEATHER", "HAIL"),
    "WTHR": ("WEATHER", "MISC"),
    "STORM": ("WEATHER", "STORM"),
    "THUN": ("WEATHER", "THUNDER"),
    "WHSTHmn": ("WHISTLES", "HUMAN"),
    "WHSTMech": ("WHISTLES", "MECHANICAL"),
    "WHSTMisc": ("WHISTLES", "MISC"),
    "WINDDsgn": ("WIND", "DESIGNED"),
    "WIND": ("WIND", "GENERAL"),
    "WINDGust": ("WIND", "GUST"),
    "WINDInt": ("WIND", "INTERIOR"),
    "WINDTonl": ("WIND", "TONAL"),
    "WINDTurb": ("WIND", "TURBULENT"),
    "WINDVege": ("WIND", "VEGETATION"),
    "WNDWCover": ("WINDOWS", "COVERING"),
    "WNDWHdwr": ("WINDOWS", "HARDWARE"),
    "WNDWKnck": ("WINDOWS", "KNOCK"),
    "WNDWMetl": ("WINDOWS", "METAL"),
    "WNDWMisc": ("WINDOWS", "MISC"),
    "WNDWPlas": ("WINDOWS", "PLASTIC"),
    "WNDWWood": ("WINDOWS", "WOOD"),
    "WINGBird": ("WINGS", "BIRD"),
    "WINGCrea": ("WINGS", "CREATURE"),
    "WINGInsc": ("WINGS", "INSECT"),
    "WINGMisc": ("WINGS", "MISC"),
    "WOODBrk": ("WOOD", "BREAK"),
    "WOODCrsh": ("WOOD", "CRASH & DEBRIS"),
    "WOODFric": ("WOOD", "FRICTION"),
    "WOODHndl": ("WOOD", "HANDLE"),
    "WOODImpt": ("WOOD", "IMPACT"),
    "WOODMisc": ("WOOD", "MISC"),
    "WOODMvmt": ("WOOD", "MOVEMENT"),
    "WOODTonl": ("WOOD", "TONAL"),
    "CKTRANSBass": ("CONSTRUCTION KIT (CK)", "TRANSIENT - Bass"),
    # Add the full list from your spreadsheet here
}

def load_config():
    if CONFIG_PATH.exists():
        with open(CONFIG_PATH, 'r') as f:
            return json.load(f)
    else:
        return {
            "drop_folder": str(Path.home() / "Desktop/SFX Drop Folder"),
            "library_root": str(Path("/Volumes/PerforceSto/SFX Library/SFX_UCS Personal Library"))
        }


def save_config(config):
    with open(CONFIG_PATH, 'w') as f:
        json.dump(config, f, indent=2)


def move_files(config):
    drop_folder = Path(config["drop_folder"])
    library_root = Path(config["library_root"])
    moved, errors = [], []

    for file in drop_folder.iterdir():
        if file.is_file() and "_" in file.name:
            catid = file.name.split("_")[0]
            if catid in UCS_MAP:
                category, subcategory = UCS_MAP[catid]
                dest_folder = library_root / category / subcategory

                if not dest_folder.exists():
                    errors.append(f"Missing folder: {dest_folder}")
                    continue

                dest_file = dest_folder / file.name
                counter = 1
                while dest_file.exists():
                    stem, ext = os.path.splitext(file.name)
                    dest_file = dest_folder / f"{stem}_{counter}{ext}"
                    counter += 1

                try:
                    shutil.move(str(file), dest_file)
                    moved.append(dest_file.name)
                except Exception as e:
                    errors.append(f"Failed to move {file.name}: {e}")
            else:
                errors.append(f"Unknown CatID: {catid}")

    result = f"Moved {len(moved)} file(s).\n"
    if errors:
        result += "\nErrors:\n" + "\n".join(errors[:10])
    return result


def run_sort(config):
    result = move_files(config)
    messagebox.showinfo("Sort Results", result)


def choose_folder(entry_widget, config_key, config):
    folder = filedialog.askdirectory()
    if folder:
        config[config_key] = folder
        entry_widget.delete(0, tk.END)
        entry_widget.insert(0, folder)
        save_config(config)


def build_ui():
    config = load_config()

    root = tk.Tk()
    root.title("UCS SFX Sorter")
    root.geometry("400x200+0+0")
    root.attributes("-topmost", True)

    # Drop folder
    tk.Label(root, text="Drop Folder").pack()
    drop_entry = tk.Entry(root, width=50)
    drop_entry.pack()
    drop_entry.insert(0, config["drop_folder"])
    tk.Button(root, text="Browse", command=lambda: choose_folder(drop_entry, "drop_folder", config)).pack()

    # Library folder
    tk.Label(root, text="Library Root Folder").pack()
    lib_entry = tk.Entry(root, width=50)
    lib_entry.pack()
    lib_entry.insert(0, config["library_root"])
    tk.Button(root, text="Browse", command=lambda: choose_folder(lib_entry, "library_root", config)).pack()

    # Sort button
    tk.Button(root, text="Sort Files", height=2, width=20,
              command=lambda: run_sort(config)).pack(pady=10)

    root.mainloop()


if __name__ == "__main__":
    build_ui()
